name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Change to music_player directory
      run: cd music_player

    - name: Install Dependencies
      run: |
        cd music_player
        npm install

    - name: Build and Release
      run: |
        cd music_player
        npm run dist
